---
tasks:
    - browserify.js
    - build.js
    - clean.js
    - connect.js
    - default.js
    - extras.js
    - fonts.js
    - html.js
    - images.js
    - serve.js
    - styles.js
    - watch.js
    - wiredep.js
app:
    options:
        frameworks      : 'bootstrap'       # raw / bootstrap
        styling         : 'less'            # less / sans / raw
        scripting       : 'coffee'          # coffee / js
        templating      : 'html'            # html / jade / nunjucks
        icons           : true
        fonts           : false
        tests           : true
    hosts:
        port            : 9000
        local           : 'http://localhost'
    files:
        npm             : '../package.json'
        bower           : '../bower.json'
        test            : '../test/index.js'
        coffeeMain      : './app/scripts/main.coffee'
        styLess         : './app/styles/main.less'
        scrMain         : './dist/main.js'
    paths:
        vendor          : './dist/js/vendor/'
        app:                                    # if any of these removed, it bypasses that task
            data        : './app/data/'
            fonts       : './app/fonts/'
            scripts     : './app/scripts/'
            styles      : './app/styles/'
            images      : './dist/images/'
        tmp:
            root        : '.tmp/'
            styles      : '.tmp/styles'
            scripts     : '.tmp/scripts'
        dist:
            root        : './dist/'
            images      : './dist/images/'
            fonts       : './dist/fonts/'
            styles      : './dist/styles/'
        assets          : '{./.tmp,./app,./dist}'
        less:
            - './app/styles/includes'
            - './dist/js/vendor/bootstrap/less'
    sources:
        wiredep         : './app/*.html'
        watch:
            - './app/*.html'
            - '.tmp/styles/**/*.css'
            - '{.tmp,app}/scripts/**/*.js'
            - 'app/images/**/*'
        styles          : './app/styles/**/*.less'
        coffeeScr       : './app/scripts/**/*.coffee'
        images          : './app/images/**/*.{gif,png,jpg,jpeg}'
        extras:
            - './app/*.*'
            - '!app/*.html'
    filters:
        scripts     : '**/*.js'
        styles      : '**/*.css'
        fonts       : '**/*.{eot,svg,ttf,woff}'
