---
tasks:
    - browserify.js
    - build.js
    - clean.js
    - connect.js
    - default.js
    - extras.js
    - fonts.js
    - lessinjector.js
    - htmlinjector.js
    - html.js
    - images.js
    - serve.js
    - styles.js
    - watch.js
    - wiredep.js
app:
    options:
        frameworks      : 'bootstrap'       # raw / bootstrap
        styling         : 'less'            # less / sans / raw
        scripting       : 'coffee'          # coffee / js
        templating      : 'html'            # html / jade / nunjucks
        less:
            - lesshat
            - preboot
        icons           : true
        footer          : true
        fonts           : false
        tests           : true
    hosts:
        port            : 9000
        local           : 'http://localhost'
    files:
        npm             : '../package.json'
        bower           : '../../bower.json'
        test            : '../test/index.js'
        coffeeMain      : './app/scripts/main.coffee'
        scrMain         : './main.js'
        lessBoot        : './app/styles/boot.less'                  # our main less-file
        lesshat         : 'lesshat/build/lesshat-prefixed.less'     # these will be the entry points of less
        preboot         : 'preboot/less/docs.less'                  # frameworks to be added to the import directive
        icons           : './app/partials/icons.html'
        footer          : './app/partials/footer.html'
    paths:
        vendor          : './app/vendor/'
        app:                                    # if any of these removed, it bypasses that task
            root        : './app/'
            files       : './app/*'
            data        : './app/data/'
            fonts       : './app/fonts/'
            scripts     : './app/scripts/'
            styles      : './app/styles/'
            images      : './app/images/'
        tmp:
            root        : './.tmp/'
            files       : './.tmp/*'
            html        : './.tmp/*.html'
            styles      : './.tmp/styles/'
            scripts     : './.tmp/scripts/'
        dist:
            root        : './dist/'
            images      : './dist/images/'
            fonts       : './dist/fonts/'
            styles      : './dist/css/'
            scripts     : './dist/js/'
        assets          : '{./.tmp,./app,./dist}'
        less:
            - './app/styles/'
            - './app/vendor/bootstrap/less/'
            - './app/vendor/preboot/less/'
    sources:
        allHtml         : './app/*.html'
        watch:
            - './app/*.html'
            - '.tmp/styles/**/*.css'
            - '{.tmp,app}/scripts/**/*.js'
            - 'app/images/**/*'
        styles          : './app/styles/**/*.less'
        coffeeScr       : './app/scripts/**/*.coffee'
        images          : './app/images/**/*.{gif,png,jpg,jpeg}'
        extras:
            - './app/*.*'
            - '!app/*.html'
            - '!app/*.less'
    filters:
        scripts     : '**/*.js'
        styles      : '**/*.css'
        fonts       : '**/*.{eot,svg,ttf,woff}'
